pub mod app;
/// Generated by Luminos Config
/// DO NOT EDIT MANUALLY!
pub mod database;

pub fn load_config() -> luminos_config::Config {
    let mut cfg = luminos_config::Config::new();
    cfg.insert_section("database", &database::config());
    cfg.insert_section("app", &app::config());
    cfg
}
